module.exports = [
    {name:'Token', type:'coin', description:'Proof that you defeated an enemy', target: [], effects: [], range:{}, stats:{}, value: 1, requirements:[]},
    {name:'Sword', type:'Main Hand', description:'Common sword', target: ['enemy'], effects: ['damage'], range:{}, stats:{ 'power': 2 }, value: 500, requirements:[{name:'level',value:1}]},
    {name:'Long Sword', type:'Main Hand', description:'Common sword', target: ['enemy'], effects: ['damage'], range:{}, stats:{ 'power': 3 }, value: 750, requirements:[{name:'level',value:1}]},
    {name:'Great Sword', type:'2-Handed', description:'Common two-handed sword', target: ['enemy'], effects: ['damage'], range:{}, stats:{ 'power': 5 }, value: 750, requirements:[{name:'level',value:3}]},
    {name:'Big Club', type:'2-Handed', description:'Small tree', target: ['enemy'], effects: ['damage'], range:{}, stats:{ 'power': 4 }, value: 750, requirements:[{name:'level',value:1}]},
    {name:'Shield', type:'Off Hand', description:'Common shield', target: [], effects: [], range:{}, stats:{ 'defense': 1 }, value: 250, requirements:[{name:'level',value:1}]},
    {name:'Buckler', type:'Off Hand', description:'Common buckler', target: [], effects: [], range:{}, stats:{ 'defense': 3 }, value: 450, requirements:[{name:'level',value:1}]},
    {name:'Leather', type:'Armor', description:'Common leather armor', target: [], effects: [], range:{}, stats:{ 'defense': 2, 'hpMax':5 }, value: 750, requirements:[{name:'level',value:1}]},
    {name:'Plate', type:'Armor', description:'Common plate armor', target: [], effects: [], range:{}, stats:{ 'defense': 5, 'hpMax':25, 'speed':-5 }, value: 1750, requirements:[{name:'level',value:3}]},
    {name:'Ring of Quickness ', type:'Ring', description:'Common Ring of speed', target: [], effects: [], range:{}, stats:{ 'speed': 5 }, value: 1000, requirements:[{name:'level',value:1}]},
    {name:'Ring of Strength', type:'Ring', description:'Common Ring of power', target: [], effects: [], range:{}, stats:{ 'power': 5 }, value: 1000, requirements:[{name:'level',value:1}]},
    {name:'Ring of Vitality', type:'Ring', description:'Common Ring of health', target: [], effects: [], range:{}, stats:{ 'hpMax': 5 }, value: 1000, requirements:[{name:'level',value:1}]},
    {name:'Ring of Healing', type:'Ring', description:'Uncommon Ring of healing', target: [], effects: [{name:'heal',uses:5,usesMax:5}], range:{min:10,max:20}, stats:{ }, value: 3000, requirements:[{name:'level',value:1}]},
    {name:'Scroll of Healing', type:'Scroll', description:`Heals a target player for 10 - 20 hp`, target: ['self','player'], effects: [{name:'heal',uses:1,usesMax:1}], range:{min:10,max:20}, stats:{}, value: 100, requirements:[]},
    {name:'Scroll of Burning', type:'Scroll', description:`Deals 30 - 50 damage to an enemy`, target: ['enemy'], effects: [{name:'burn',uses:1,usesMax:1}], range:{min:30,max:50}, stats:{}, value: 300, requirements:[]},
    {name:'Healing Potion', type:'Potion', description:`Heals self for 25 - 50 hp`, target: ['self'], effects: [{name:'heal',uses:1,usesMax:1}], range:{min:25,max:50}, stats:{}, value: 200, requirements:[]},
    
    {name:'Spell Book', type:'Class', description:`Allows casting of spells`, target: ['self'], effects: [{name:'heal',uses:1,usesMax:1}], range:{min:25,max:50}, stats:{}, value: 200, requirements:[]},
    {name:'Sculpting Tools', type:'Class', description:`Allows summoning of monsters. Requires Sculpting Clay.`, target: ['self'], effects: [{name:'heal',uses:1,usesMax:1}], range:{min:25,max:50}, stats:{}, value: 200, requirements:[]},
    {name:'Guantlets', type:'Class', description:`Gives you the ability to survive where others have fallen.`, target: ['self'], effects: [{name:'heal',uses:1,usesMax:1}], range:{min:25,max:50}, stats:{}, value: 200, requirements:[]},
    {name:'Blood Crystal', type:'Class', description:`Allows to heal others at a cost.`, target: ['self'], effects: [{name:'heal',uses:1,usesMax:1}], range:{min:25,max:50}, stats:{}, value: 200, requirements:[]},
    {name:'Ceremonial Mask', type:'Class', description:`Allows the use of buffs and curses.`, target: ['self'], effects: [{name:'heal',uses:1,usesMax:1}], range:{min:25,max:50}, stats:{}, value: 200, requirements:[]},
    {name:'War Paint', type:'Class', description:`Gives you unparalled melee abilities.`, target: ['self'], effects: [{name:'heal',uses:1,usesMax:1}], range:{min:25,max:50}, stats:{}, value: 200, requirements:[]},
];
